### ISSUE TITLE
Config Help - No containers found

### ISSUE THREAD

**Issue by samcro1967** [DVDAndroid/glance-docker-container-ext#4]
I am not having any luck getting this working.  Not seeing any errors in the logs. 

**docker logs glance:**
```
2024/08/28 06:51:28 INFO Starting server host="" port=8080
```

**docker logs glance-docker-container-ext**
```
2024/08/28 11:53:29 INFO starting webserver host="" port=8101
```

**relevant glance.yml config**
```
  - name: Docker
    columns:
      - size: full
        widgets:
          - type: extension
            allow-potentially-dangerous-html: true
            url: http://192.168.1.104:8101
            cache: 5m
            parameters:
              title: Docker Containers
              all: true
              order: name,status
```

**Docker Tab screenshot**
![image](https://github.com/user-attachments/assets/096b5d95-4c38-4eff-9bb4-051039f1658c)

**curl result**
```
curl http://192.168.1.104:8101
<p>No containers found</p>
```

**Docker Compose**
```
services:
  glance:
    hostname: glance
    image: glanceapp/glance
    container_name: glance
    restart: always
    environment:
      - GITHUB_TOKEN=${GHCR_TOKEN_WHATSUPDOCKER}
    volumes:
      - ${docker}/glance/glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8092:8080
    networks:
      - wg-pia
  glance-docker-container-ext:
    hostname: glance-docker-container-ext
    image: dvdandroid/glance-docker-container-ext:latest
    container_name: glance-docker-container-ext
    restart: always
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT=8101
    ports:
     - 8101:8101
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - wg-pia
  beszel:
    hostname: beszel
    image: henrygd/beszel
    container_name: beszel
    restart: always
    ports:
      - 8115:8090
    volumes:
      - ${docker}/beszel:/beszel_data
    labels:
      - glance.enable=true
      - glance.name=Beszel
      - glance.description=Test
      - glance.group=Test
      - glance.url=http://192.168.1.104:8115/
      - glance.icon="si:Jellyfin"
    networks:
      - wg-pia
    extra_hosts:
      - host.docker.internal:host-gateway
```

**Comment by DVDAndroid** [comment]
Hi, you are defining container `beszel` in a group called "Test" (`glance.group=Test`), but you are not declaring any group with that identifier.
Try removing that label or edit the glance configuration like this:
```
  - name: Docker
    columns:
      - size: full
        widgets:
          - type: extension
            allow-potentially-dangerous-html: true
            url: http://192.168.1.104:8101
            cache: 5m
            parameters:
              title: Docker Containers
              all: true  - name: Docker
    columns:
      - size: full
        widgets:
          - type: extension
            allow-potentially-dangerous-html: true
            url: http://192.168.1.104:8101
            cache: 5m
            parameters:
              title: Docker Containers
              all: true
              group: Test
              order: name,status
```

Let me know
